# Generated by Django 5.2.5 on 2025-08-09 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="time_to_complete",
        ),
        migrations.AddField(
            model_name="habit",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите связанную привычку",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="habits",
                to="habits.habit",
                verbose_name="Связанная привычка",
            ),
        ),
    ]
