# Generated by Django 5.2.5 on 2025-08-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_habit_time_to_complete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.CharField(
                blank=True,
                help_text="Укажите время",
                max_length=150,
                null=True,
                verbose_name="Время",
            ),
        ),
    ]
