# Generated by Django 5.2.5 on 2025-08-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_alter_habit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='interval',
            field=models.PositiveSmallIntegerField(blank=True, default=1, help_text='Укажите периодичность', null=True, verbose_name='Периодичность'),
        ),
    ]
