# Generated by Django 5.2.5 on 2025-08-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0008_alter_habit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='interval',
            field=models.PositiveSmallIntegerField(blank=True, default=1, help_text='Укажите периодичность в днях', null=True, verbose_name='Периодичность'),
        ),
    ]
